# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunghwan_park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='my_score',
            field=models.FloatField(default=0.0),
        ),
    ]
