# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sunghwan_park', '0002_movie_my_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='my_comment',
            field=models.TextField(default=''),
        ),
    ]
